### ISSUE TITLE
conflict with aiohttp 2.0.0.a1

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp-debugtoolbar#115]
ref https://github.com/aio-libs/aiohttp/issues/1714

```
Traceback (most recent call last):
  File "/home/samuel/code/aiohttp-devtools/env/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 417, in start
    resp = yield from self._request_handler(request)
  File "/home/samuel/code/aiohttp-devtools/env/lib/python3.5/site-packages/aiohttp/web.py", line 259, in _handle
    resp = yield from handler(request)
  File "/home/samuel/code/aiohttp-devtools/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/middlewares.py", line 135, in toolbar_middleware
    yield from toolbar.process_response(request, response)
  File "/home/samuel/code/aiohttp-devtools/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/toolbar.py", line 48, in process_response
    yield from panel.process_response(response)
  File "/home/samuel/code/aiohttp-devtools/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/panels/request_vars.py", line 32, in process_response
    for k in sorted(request.POST)],
AttributeError: 'Request' object has no attribute 'POST'
```

Let me know if more details are required.

**Comment by jettify** [comment]
@samuelcolvin would you like to create PR with fix?

**Comment by doubledare704** [comment]
Same with 2.0.1

**Comment by samuelcolvin** [comment]
yes, will try I'm pretty busy atm.

Perhaps someone could give me access to the repo?

**Comment by doubledare704** [comment]
@samuelcolvin, fork and pull request)

**Comment by samuelcolvin** [comment]
Really?! I'd never heard of that.

If I'm managing aiohttp-devtools and have member access to aiohttp itself I would say it would make sense to have member access to aiohttp-debugtoolbar too.

**Comment by doubledare704** [comment]
@samuelcolvin I saw you're contributing in aio-libs, but seems authors have not granted all access to you.

**Comment by jettify** [comment]
@samuelcolvin gave you access

**Comment by jettify** [comment]
sorry, missed your messages

**Comment by jettify** [comment]
i believe we can close this isseue

**Comment by cpwr** [comment]
still having the problem in 
aiohttp==2.0.7
aiohttp-debugtoolbar==0.3.0

**Comment by doubledare704** [comment]
@cpwr , because author made no update version for fixes to latest aio
try install from master, it has latest updates.

**Comment by jettify** [comment]
sorry for that, will do release tonight

**Comment by jettify** [comment]
new version released to PyPI https://pypi.python.org/pypi/aiohttp_debugtoolbar/0.4.0
