### ISSUE TITLE
Error when work with `__call__` request handler

### ISSUE THREAD

**Issue by phyng** [aio-libs/aiohttp-debugtoolbar#224]
## env

- Python 3.7
- aiohttp==3.3.2
- aiohttp-wsgi==0.8.1
- aiohttp-debugtoolbar==0.5.0

## exception

```
[2018-08-14 15:15:47 +0800] [55447] [ERROR] Error handling request
Traceback (most recent call last):
  File "/Users/phyng/.virtualenvs/dcode3.7/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/Users/phyng/.virtualenvs/dcode3.7/lib/python3.7/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/Users/phyng/.virtualenvs/dcode3.7/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/Users/phyng/.virtualenvs/dcode3.7/lib/python3.7/site-packages/aiohttp_debugtoolbar/middlewares.py", line 59, in toolbar_middleware
    toolbar = DebugToolbar(request, panel_classes, global_panel_classes)
  File "/Users/phyng/.virtualenvs/dcode3.7/lib/python3.7/site-packages/aiohttp_debugtoolbar/toolbar.py", line 30, in __init__
    panel_inst = panel_class(request)
  File "/Users/phyng/.virtualenvs/dcode3.7/lib/python3.7/site-packages/aiohttp_debugtoolbar/panels/routes.py", line 21, in __init__
    self.populate(request)
  File "/Users/phyng/.virtualenvs/dcode3.7/lib/python3.7/site-packages/aiohttp_debugtoolbar/panels/routes.py", line 33, in populate
    "source": inspect.getsource(route.handler)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 968, in getsource
    lines, lnum = getsourcelines(object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 768, in findsource
    file = getsourcefile(object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 684, in getsourcefile
    filename = getfile(object)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 666, in getfile
    type(object).__name__))
TypeError: module, class, method, function, traceback, frame, or code object was expected, got WSGIHandler
```

## WSGIHandler

https://github.com/etianen/aiohttp-wsgi/blob/master/aiohttp_wsgi/wsgi.py

```py
class WSGIHandler:

    async def handle_request(self, request):
        pass

    __call__ = handle_request
```

**Comment by monokrome** [comment]
Similar error here when using a `functools.partial` object :crying_cat_face:
