### ISSUE TITLE
aiohttp-debugtoolbar seem to throw an error with aiohttp 1.1.1

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp-debugtoolbar#54]
Not exactly sure when this error started occurring but with aiohttp 1.1.1 I'm now getting the follow ing error whenever the app throws an exception.

Let me know if you need any more specific information.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<path>/env/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/<path>/env/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
    resp = yield from handler(request)
  File "/<path>/app/middleware.py", line 33, in user_middleware_handler
    return await handler(request)
  File "/<path>/app/middleware.py", line 40, in error_middleware_handler
    return await handler(request)
  File "/<path>/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/middlewares.py", line 105, in toolbar_middleware
    body = tb.render_full(request).encode('utf-8', 'replace')
  File "/<path>/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/tbtools/tbtools.py", line 201, in render_full
    summary = self.render_summary(request.app, include_title=False)
  File "/<path>/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/tbtools/tbtools.py", line 180, in render_summary
    frame.render()
  File "/<path>/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/tbtools/tbtools.py", line 283, in render
    'current_line': escape(self.current_line.strip())
  File "/<path>/env/lib/python3.5/site-packages/aiohttp_debugtoolbar/tbtools/tbtools.py", line 368, in current_line
    return self.sourcelines[self.lineno - 1]
  File "/<path>/env/lib/python3.5/site-packages/aiohttp/helpers.py", line 478, in __get__
    val = inst._cache.get(self.name, _sentinel)
AttributeError: 'Frame' object has no attribute '_cache'
```

**Comment by asvetlov** [comment]
Thanks for report!
